import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Header } from '@/components/shared/Header/Header';
import { Footer } from '@/components/shared/Footer';
import { Description } from '@/components/Home/Description';
import { Hero } from '@/components/Home/Hero';
import '@/sass/globals.scss';

const roboto = Roboto({
	weight: ['100', '300', '500', '700', '900'],
	subsets: ['latin-ext'],
});

export const metadata: Metadata = {
	title: 'Future Eccomerce',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<Header />
				<Hero />
				<Description />
				{children}
				<Footer />
			</body>
		</html>
	);
}
